# Generated by Django 3.1 on 2021-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=200)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoListItem',
        ),
    ]
